#server:
#  port: 9000
#
#person:
#  lastName: zhangsan
#  age: 18
#  boss: true
#  birth: 2000/11/11
#  maps: {k1: v1,k2: 12}
#  lists:
#    - lisi
#    - wangwu
#  dog:
#    name: dahuang
#    age: 3