server:
  port: 9000

mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  mapper-locations: classpath:mapper/*.xml                       # mapper映射文件
  type-aliases-package: com.example.demo.model

spring:
  datasource:
    #mysql配置
#    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
#    url: jdbc:mysql://localhost:3306/logintest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8            # 数据库名称
#    username: root
#    password: root

#    oracle配置
    driver-class-name: oracle.jdbc.driver.OracleDriver              # oracle驱动包
    url: jdbc:oracle:thin:@192.168.35.29:1521:orcl      # 数据库名称
    username: mtest
    password: mtest!123ff